cmake_minimum_required(VERSION 2.8.3)

file(READ "${CMAKE_CURRENT_LIST_DIR}/config/OnRobotSG_preamble.script" CS)
file(WRITE "${CMAKE_CURRENT_LIST_DIR}/src/OnRobotSG_preamble.h" "// Generated by generate_preamble_str.cmake\n// from generate_preamble_str.cl\n#include <string>\n static const std::string ON_ROBOT_SG_PREAMBLE_STR = R\"2e9661acc(${CS})2e9661acc\";")